services:
  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.21.0
    command:
      - "--address=0.0.0.0"
      - "--port=3306"
      - "project-61ceee4c-ef41-4d6e-a40:asia-northeast3:share-todo-database"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 3306 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    image: asia-northeast3-docker.pkg.dev/project-61ceee4c-ef41-4d6e-a40/share-todo-back/app:latest
    env_file:
      - ./.env.prod
    depends_on:
      - cloudsql
      - redis
    restart: unless-stopped
    expose:
      - "8080"

  nginx:
    image: asia-northeast3-docker.pkg.dev/project-61ceee4c-ef41-4d6e-a40/share-todo-front/nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # 호스트에 있는 nginx 설정 파일을 컨테이너에 마운트
      - /deploy/share-todo-front/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

      # Let's Encrypt 인증서/챌린지용 볼륨
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h;
      done"

volumes:
  redis_data:
  letsencrypt:
  certbot_www:
